services:
  - name: catubig-user-management-frontend
    type: web
    env: static
    rootDir: Angular-10-Boilerplate
    buildCommand: npm install --legacy-peer-deps && npm run build -- --configuration production
    staticPublishPath: dist/angular-signup-verification-boilerplate
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html