services:
  - name: monreal-user-management
    type: web
    env: node
    plan: free
    rootDir: Node-js-MySQL-BoilerPlate
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production