services:
  - name: catubig-user-management-backend
    type: web
    env: node
    plan: free
    rootDir: node.js
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production